minimumsquare: 4
distanciaEntreSnapshots: 30
segundosEntreInstantes: 30
instantesHastaDesaparicion: 7
metrosPorCelda: 50

#En metros segundo
velocidadMaxima: 33.33 

limites: 16000
minimumSquare: 4

# SC Dense Codes
S: 8
C: 8

chunkSize: 4

logging:
  level:
    ROOT: INFO

