name: develname
env: develYML
servers: 
  - develserver1
  - develserver2
numbers:
  - 1
  - 6
minimumsquare: 4
distanciaEntreSnapshots: 1
segundosEntreInstantes: 30
metrosPorCelda: 30

#En metros segundo
velocidadMaxima: 33.33 

limites: 16000
minimumSquare: 4

---

spring:
 profiles: development
name: develname
env: develYML
servers: 
  - develserver1
  - develserver2
numbers:
  - 1
  - 6
minimumsquare: 4
distanciaEntreSnapshots: 1
segundosEntreInstantes: 30
metrosPorCelda: 30

#En metros segundo
velocidadMaxima: 33.33 

limites: 10000
minimumSquare: 4

  
---
spring:
 profiles: production
name: prodname
env: prodYML
servers: 
  - prodserver1
  - prodserver2
numbers:
  - 1
  - 6
minimumsquare: 4
distanciaEntreSnapshots: 20
segundosEntreInstantes: 30
metrosPorCelda: 30

#En metros segundo
velocidadMaxima: 33.33 

limites: 10000
minimumSquare: 4